import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const farms = {
  farm1: { name: 'گله آقای محمدی', total: 580, sick: 18, pregnant: 210, weight: 55, births: 28, deaths: 3, sale: 42, feedDays: 9 },
  farm2: { name: 'گله شرکت دامپروری', total: 1250, sick: 9, pregnant: 430, weight: 48, births: 65, deaths: 5, sale: 110, feedDays: 16 },
  farm3: { name: 'گله آقای رضایی', total: 380, sick: 23, pregnant: 140, weight: 42, births: 19, deaths: 4, sale: 35, feedDays: 7 },
};

const roles = [
  ['farmer', '🐑', 'دامدار', 'مالک گله، مدیریت کامل'],
  ['vet', '🩺', 'دامپزشک', 'چند گله، سلامت و درمان'],
  ['nutritionist', '🥬', 'مشاور تغذیه', 'چند گله، جیره‌نویسی'],
  ['vaccinator', '💉', 'واکسیناتور', 'برنامه واکسن'],
  ['supplier', '🏪', 'تأمین‌کننده نهاده', 'فروش نهاده'],
  ['butcher', '🥩', 'خریدار / قصاب', 'خرید دام'],
];

const menus = {
  farmer: [['overview','🏠','نمای کلی'],['animals','🐑','دام‌ها'],['breeding','🧬','تولیدمثل'],['health','🩺','سلامت'],['nutrition','🥬','تغذیه و خوراک'],['accounting','💰','حسابداری دام'],['sales','💵','فروش'],['inventory','📦','انبار'],['forecast','📈','پیش‌بینی'],['ai','🤖','دستیار هوشمند']],
  vet: [['overview','🏥','نمای کلی سلامت'],['farms','🐑','گله‌های تحت پوشش'],['health','🩺','سلامت و بیماری'],['treatment','💊','درمان'],['vaccination','💉','واکسیناسیون'],['reproduction','🧬','تولیدمثل'],['mortality','⚠️','تلفات'],['animals','📋','پرونده دام‌ها'],['alerts','🔔','هشدارها']],
  nutritionist: [['overview','🥬','نمای کلی تغذیه'],['farms','🐑','گله‌های تحت پوشش'],['rations','📋','جیره‌ها'],['feed','🌾','نهاده و خوراک'],['performance','📈','عملکرد'],['feedcost','💰','اقتصاد خوراک'],['groups','🐏','گروه‌های تغذیه‌ای'],['alerts','🔔','هشدارها']],
  vaccinator: [['overview','💉','نمای کلی'],['schedule','📅','برنامه واکسیناسیون'],['today','🗓️','عملیات امروز'],['farms','🐑','گله‌ها'],['records','📋','سوابق واکسن'],['inventory','📦','موجودی واکسن'],['alerts','🔔','هشدارها']],
  supplier: [['overview','🏪','نمای کلی'],['customers','👥','مشتریان'],['orders','🛒','سفارش‌ها'],['inventory','📦','انبار'],['sales','💰','فروش'],['receivables','💳','مطالبات'],['forecast','📈','پیش‌بینی سفارش'],['ai','🤖','هوش تجاری']],
  butcher: [['overview','🥩','نمای کلی بازار'],['available','🐑','دام‌های آماده فروش'],['market','📈','بازار و قیمت'],['purchases','🛒','خریدها'],['suppliers','👥','فروشندگان'],['transport','🚚','حمل‌ونقل'],['margin','💰','حاشیه سود'],['alerts','🔔','هشدارها']],
};

function Metric({label,value,icon,tone=''}) { return <div className={`metric ${tone}`}><span className="metric-icon">{icon}</span><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>; }
function Alert({children,tone='yellow'}) { return <div className={`alert ${tone}`}>{children}</div>; }

function Onboarding({onSelect}) {
  return <section className="onboarding"><div className="brand"><div>SHABAN</div><small>زیرساخت هوشمند زنجیره دام سبک</small></div><h2>نقش خود را انتخاب کنید تا محیط اختصاصی شما فعال شود</h2><div className="role-grid">{roles.map(([id,icon,name,desc])=><button className="role-card" key={id} onClick={()=>onSelect(id)}><b>{icon}</b><strong>{name}</strong><small>{desc}</small></button>)}</div></section>;
}

function FarmSelection({role,onChoose,onBack}) {
  const title = role === 'vet' ? 'گله‌های تحت پوشش دامپزشک' : role === 'nutritionist' ? 'گله‌های تحت پوشش مشاور تغذیه' : role === 'vaccinator' ? 'گله‌های تحت پوشش واکسیناتور' : role === 'supplier' ? 'مشتریان تأمین‌کننده نهاده' : 'گله‌های قابل خرید';
  return <section className="farm-step"><div className="farm-panel"><h2>{title}</h2><p>گله موردنظر را انتخاب کنید</p>{Object.entries(farms).map(([id,f])=><button className="farm-item" key={id} onClick={()=>onChoose(id)}><span className="farm-icon">{roles.find(r=>r[0]===role)?.[1] || '🐑'}</span><span><strong>{f.name}</strong><small>{f.total.toLocaleString('fa-IR')} رأس | {f.sick} بیمار | {f.feedDays} روز خوراک</small></span><em>{f.sick > 20 ? 'نیازمند بررسی' : 'سالم'}</em></button>)}<button className="back-btn" onClick={onBack}>↩️ تغییر نقش</button></div></section>;
}

function Table({headers,rows}) { return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }

function Page({title,subtitle,children}) { return <><div className="breadcrumb">شبان › {title}</div><div className="hero"><h2>{title}</h2><p>{subtitle}</p></div>{children}</>; }

function FarmerPage({page,f}) {
  if(page==='overview') return <><Page title="نمای اقتصادی و مدیریتی گله" subtitle="تمام اطلاعات گله، تولید، سلامت، تولیدمثل و اقتصاد دام در یک نگاه."><div className="metric-grid">{[["کل دام",f.total,'🐑'],['دام بیمار',f.sick,'🩺','danger'],['دام آبستن',f.pregnant,'🧬','info'],['متوسط وزن',`${f.weight} kg`,'⚖️'],['تولد ماه جاری',f.births,'🐣','info'],['تلفات ماه',f.deaths,'⚠️','danger'],['دام آماده فروش',f.sale,'💰'],['موجودی خوراک',`${f.feedDays} روز`,'🌾','warning']].map((x,i)=><Metric key={i} label={x[0]} value={x[1]} icon={x[2]} tone={x[3]}/>)}</div><div className="two-col"><div className="card"><h3>اقتصاد گله</h3><div className="kpis"><Metric label="درآمد ماه" value="۱۸۶ میلیون" icon="💵"/><Metric label="هزینه ماه" value="۱۳۲ میلیون" icon="💸" tone="danger"/><Metric label="سود ماه" value="۵۴ میلیون" icon="📈"/><Metric label="هزینه خوراک" value="۴۲.۸ میلیون/روز" icon="🌾"/></div></div><div className="card"><h3>هشدارهای مدیریتی</h3><Alert tone="danger">🔴 {f.sick} دام بیمار یا تحت پایش هستند.</Alert><Alert>⚠️ موجودی خوراک فقط {f.feedDays} روز کافی است.</Alert><Alert tone="green">🟢 {f.sale} رأس در محدوده مناسب فروش قرار دارند.</Alert></div></div><div className="card"><h3>وضعیت گروه‌های گله</h3><Progress label="میش" value={f.total-f.rams-f.lambs} total={f.total}/><Progress label="قوچ" value={f.rams} total={f.total}/><Progress label="بره" value={f.lambs} total={f.total}/></div><Panorama/></Page><Assistant/></>;
  if(page==='animals') return <Page title="🐑 پرونده اقتصادی دام‌ها" subtitle="مشاهده وضعیت، هزینه تجمعی، ارزش و سود هر رأس"><div className="card"><Table headers={['دام','نژاد','سن','وزن','هزینه تجمعی','ارزش فعلی','سود بالقوه']} rows={[["S-0354",'افشاری','۳۲ ماه','۶۳ kg','۹.۲ میلیون','۱۱.۲ میلیون','۲ میلیون'],['S-0481','افشاری','۵ ماه','۴۸ kg','۲ میلیون','۴.۲ میلیون','۲.۲ میلیون'],['S-0482','افشاری','۵ ماه','۴۶ kg','۱.۸ میلیون','۴ میلیون','۲.۲ میلیون']]}/></div></Page>;
  if(page==='health') return <Page title="🩺 سلامت گله" subtitle="سلامت، درمان، واکسیناسیون و قرنطینه"><div className="metric-grid">{[["سالم",f.total-f.sick,'🟢'],['بیمار',f.sick,'🔴','danger'],['تحت درمان',14,'💊','warning'],['قرنطینه',2,'🚨','danger']].map((x,i)=><Metric key={i} label={x[0]} value={x[1]} icon={x[2]} tone={x[3]}/>)}</div><div className="card"><Table headers={['شماره','گله','نژاد','وضعیت','تشخیص','درمان','قرنطینه']} rows={[["S-1034",'محمدی','افشاری','بیمار','پنومونی','در حال درمان','خیر'],['S-1042','رضایی','افشاری','پایش','مشکوک','—','بله']]}/></div></Page>;
  if(page==='nutrition') return <Page title="🥬 تغذیه و خوراک" subtitle="مصرف خوراک و اقتصاد جیره"><div className="metric-grid">{[["هزینه روزانه",'۴۲.۸ میلیون','💰'],['هزینه/رأس','۷۳,۸۰۰','🐑'],['موجودی خوراک',`${f.feedDays} روز`,'🌾','warning'],['جیره فعال','۴','📋','info']].map((x,i)=><Metric key={i} label={x[0]} value={x[1]} icon={x[2]} tone={x[3]}/>)}</div><div className="card"><h3>مواد اولیه مصرفی</h3><Progress label="یونجه" value={78} total={100}/><Progress label="جو" value={65} total={100}/><Progress label="ذرت" value={48} total={100}/><button className="primary">🥬 ورود به موتور جیره‌نویسی</button></div></Page>;
  if(page==='accounting') return <Page title="💰 حسابداری دام" subtitle="اتصال حسابداری به تک‌تک دام‌ها"><div className="metric-grid">{[["درآمد ماه",'۱۸۶ میلیون','💵'],['هزینه ماه','۱۳۲ میلیون','💸','danger'],['سود ماه','۵۴ میلیون','📈'],['کسری نقدینگی','۲۳ روز آینده','⚠️','warning']].map((x,i)=><Metric key={i} label={x[0]} value={x[1]} icon={x[2]} tone={x[3]}/>)}</div><div className="card"><h3>بهای تمام‌شده نمونه یک دام</h3><Table headers={['نوع هزینه','مبلغ','سهم از کل']} rows={[["خوراک",'۴,۸۰۰,۰۰۰','۵۶.۸٪'],['دارو','۶۵۰,۰۰۰','۷.۷٪'],['تولیدمثل','۷۵۰,۰۰۰','۸.۹٪'],['نیروی انسانی','۹۵۰,۰۰۰','۱۱.۲٪']]}/></div></Page>;
  const titles={breeding:['🧬 تولیدمثل','وضعیت آبستنی، زایش و عملکرد تولیدمثلی'],sales:['💵 فروش هوشمند','ارزیابی اقتصادی فروش هر دام'],inventory:['📦 انبار','موجودی نهاده و نقطه سفارش'],forecast:['📈 پیش‌بینی','پیش‌بینی نقدینگی، هزینه و فروش'],ai:['🤖 دستیار هوشمند مالی و مدیریتی','تحلیل خودکار گله و پیشنهاد اقدام']}; const t=titles[page]||titles.ai;
  return <Page title={t[0]} subtitle={t[1]}><div className="card"><Alert tone={page==='forecast'?'yellow':'green'}>{page==='sales'?`🟢 ${f.sale} رأس در محدوده مناسب فروش هستند.`:page==='inventory'?`⚠️ موجودی خوراک ${f.feedDays} روز است؛ نقطه سفارش را بررسی کنید.`:page==='forecast'?'⚠️ احتمال کسری نقدینگی در ۲۳ روز آینده.':'🟢 تحلیل شبان آماده است و اقدامات اولویت‌دار را پیشنهاد می‌کند.'}</Alert><Table headers={['شاخص','مقدار','وضعیت']} rows={[["گله",f.name,'فعال'],['کل دام',f.total,'مناسب'],['دام بیمار',f.sick,f.sick>20?'نیازمند اقدام':'پایش'],['دام آماده فروش',f.sale,'قابل بررسی']]}/></div></Page>;
}

function Progress({label,value,total}) { const p=Math.round(value/total*100); return <div className="progress-item"><div><span>{label}</span><span>{value.toLocaleString('fa-IR')} ({p}٪)</span></div><div className="progress"><i style={{width:`${p}%`}}/></div></div>; }
function Panorama(){ return <div className="card"><h3>🐑 نمای زنده گله</h3><div className="panorama">{Array.from({length:36},(_,i)=><button key={i} className="animal-dot" style={{left:`${5+(i*17)%90}%`,top:`${10+(i*31)%78}%`}} title={`دام S-${350+i}`}>🐑</button>)}</div><small className="muted">برای مشاهده پرونده دام روی هر دام کلیک کنید.</small></div>; }
function Assistant(){ const [text,setText]=useState(''); const [messages,setMessages]=useState(['سلام! برای تحلیل، پیش‌بینی و تصمیم‌گیری سؤال بپرسید.']); return <div className="card"><div className="assistant-head"><span>🧠</span><div><strong>دستیار هوشمند شبان</strong><small>تحلیلگر ۴ سطحی</small></div></div><div className="chat">{messages.map((m,i)=><div className={i%2?'msg me':'msg'} key={i}>{m}</div>)}</div><div className="input-row"><input value={text} onChange={e=>setText(e.target.value)} placeholder="مثلاً: وضعیت اقتصادی گله در ۶ ماه آینده؟"/><button className="primary" onClick={()=>{if(!text)return;setMessages([...messages,text,'تحلیل انجام شد: روند فعلی گله نیازمند پایش سلامت و کنترل هزینه خوراک است.']);setText('')}}>تحلیل</button></div></div>; }

function GenericRolePage({role,page}) { const names={vet:'دامپزشک',nutritionist:'مشاور تغذیه',vaccinator:'واکسیناتور',supplier:'تأمین‌کننده نهاده',butcher:'خریدار / قصاب'}; const f=farms.farm1; return <Page title={`${roles.find(r=>r[0]===role)?.[1]} ${menus[role].find(m=>m[0]===page)?.[2]||names[role]}`} subtitle={role==='vet'?'پایش سلامت، بیماری، درمان و تلفات گله‌های تحت پوشش':'مدیریت تخصصی زنجیره دام سبک'}><div className="metric-grid"><Metric label="گله‌های تحت پوشش" value="۳" icon="🐑"/><Metric label="کل دام‌ها" value={f.total+farms.farm2.total+farms.farm3.total} icon="🐏"/><Metric label="موارد نیازمند اقدام" value={f.sick} icon="⚠️" tone="danger"/><Metric label="عملیات امروز" value="۱۲" icon="📋" tone="info"/></div><div className="card"><Table headers={['گله','تعداد دام','شاخص اصلی','وضعیت']} rows={Object.values(farms).map(x=>[x.name,x.total,role==='nutritionist'?`${x.feedDays} روز خوراک`:role==='vet'?`${x.sick} بیمار`:`${x.sale} رأس آماده فروش`,x.sick>20?'نیازمند بررسی':'مناسب'])}/></div></Page>; }

function App(){ const [role,setRole]=useState(null); const [farm,setFarm]=useState('farm1'); const [page,setPage]=useState('overview'); const f=farms[farm]; if(!role)return <Onboarding onSelect={r=>{setRole(r);setPage('overview')}}/>; if(role!=='farmer' && !farm)return <FarmSelection role={role} onChoose={k=>setFarm(k)} onBack={()=>setRole(null)}/>; return <div className="app"><aside className="sidebar"><div className="side-brand"><b>SHABAN</b><small>سامانه هوشمند دام سبک</small></div><div className="role-current">{roles.find(r=>r[0]===role)?.[1]} {roles.find(r=>r[0]===role)?.[2]}</div><nav>{menus[role].map(([id,icon,label])=><button className={page===id?'active':''} key={id} onClick={()=>setPage(id)}><span>{icon}</span>{label}</button>)}</nav><button className="change" onClick={()=>setRole(null)}>تغییر نقش</button></aside><main className="main"><header><div><h1>{roles.find(r=>r[0]===role)?.[1]} {roles.find(r=>r[0]===role)?.[2]}</h1><p>سامانه هوشمند مدیریت زنجیره دام سبک</p></div><div className="header-actions"><button>🔔</button><select value={farm} onChange={e=>setFarm(e.target.value)}>{Object.entries(farms).map(([k,x])=><option key={k} value={k}>{x.name}</option>)}</select></div></header>{role==='farmer'?<FarmerPage page={page} f={f}/>:<GenericRolePage role={role} page={page}/>}</main></div>; }

createRoot(document.getElementById('root')).render(<App />);
